language: node_js

node_js:
    - '0.10'

before_install:
    # download and start selenium server - thought that it is not necessary, but without the website is not available within SauceLabs.
    # download selenium server - when updating the jar: adapt the SELENIUMVERSION in the test files, too
    # Lastest version: http://www.seleniumhq.org/download/
    - curl -O https://selenium-release.storage.googleapis.com/2.50/selenium-server-standalone-2.50.1.jar
    # Download and install the chromedriver to be able to execute the browser tests locally
    # Latest version: https://sites.google.com/a/chromium.org/chromedriver/downloads
    - curl https://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip > chromedriver_linux64.zip && unzip chromedriver_linux64.zip && sudo cp chromedriver /usr/local/bin && sudo chmod +rx chromedriver /usr/local/bin/chromedriver
    # start this before installation to let the server be up and ready without extra waiting time.
    - java -jar selenium-server-standalone-2.50.1.jar -Dwebdriver.chrome.driver=./chromedriver &
    # install phantomjs, too: - TODO: try the existing one from the CI environment
    - sudo apt-get install phantomjs
    #- sleep 15 works only on Win7/chrome44 and Win7/ie11
    - sleep 15
    #- echo "$(date +%H:%M:%S.%N) - before_install end"


before_script:
    #- sudo npm install - is automatically executed when install is missing
    # node app.js is started in postinstall of npm install
    # - node app.js &
    # check that the web app is running:
    - wget http://localhost:3000/authors || true
    # show the beginning of the file - the whole file is not displayed within TRAVIS (because line is too long?)
    - cat authors | cut -d'/' -f1

script:
# automatically runs `npm test` - therefore the call to mocha is located in package.json
    #- mocha --reporter spec
    #- export TEST_RUN_LOCAL=true && npm test
    #- echo "Run the same tests as above, but using the remote browser."
    - export TEST_RUN_LOCAL=false && npm test

addons:
  sauce_connect: true

env:
  global:
    - secure: "EvQvxbIQRYDF2NvRDlC8tLeoKabuhi9D+d9y89jsVniyAkMd6HXzU6N+/rsKWnLSYg4fDzadHvXUN+ge9BP1JwMFsH1OOCifBCQQLfnrZQ1phnQEhwl8LDQHVZbRv9Wsk474+NcGkGiDOrjUjbadR6YCrisPt3CHAB1XQw4zIzE="
    - secure: "sAGCSM9rCbANjWeeLnF8i2y450c4EPGUuhlOeFCxnlisduDkiQ6sZgusOlL2NiPQwmHTCcVNn7reBcuUGg1NZJfRt4NMju9OtqzS/JLk2RW9+J3zUkDrx5tQhaivWlThakRAIpNeHpCBEL9tWk68pDZw+Bfc1e1Jh4H3ji91KtI="

# Use platform configurator https://docs.saucelabs.com/reference/platforms-configurator
# Get the names and versions from the node.js tab in the section "COPY CODE".
# Use underscore for spaces in platform and browser names - they are replaced inside js.
  matrix:
    - _BROWSER: "firefox"
      _PLATFORM: "Linux"
      _VERSION: "43.0"
    - _BROWSER: "firefox"
      _PLATFORM: "Windows_7"
      _VERSION: "43.0"
    - _BROWSER: "chrome"
      _PLATFORM: "Windows_7"
      _VERSION: "47.0"
    - _BROWSER: "internet_explorer"
      _PLATFORM: "Windows_7"
      _VERSION: "11.0"
# navigation on the 'page test' does not work - no idea why 8-(
    - _BROWSER: "microsoftedge"
      _PLATFORM: "Windows_10"
      _VERSION: "20.10240"
